blank_issues_enabled: false
contact_links:
  - name: Question 🤷🏻‍♂️
    url: https://github.com/verdaccio/verdaccio/discussions/new?category=q-a
    about: 🆕 Open a new Q&A discussion 🙏
  - name: Security Report 🛡
    url: https://github.com/verdaccio/verdaccio/security/policy
    about: I want to report a security vulnerability
  - name: Chat 🏘
    url: https://discord.gg/7qWJxBf
    about: Quick question? Try out Discord chat, you can get faster feedback
